# These are supported funding model platforms

gmail email: # Griggorii@gmail.com not collabration job google corporation


I can port various tools, I need disks and a lot of space and some kind of cool corporation which needs not an employee wiping his pants at work, but the result of really generated computers of files, and not flood my eyes with tons of code that then may not be preregistered, in particular, I am that very worker X who created a lot, but is waiting for investment, not theft of technology and rewriting


This package could not be compiled in deb just because there was not enough space by the chut method into a mixed 16.04 system which consisted of packages ubuntu xenial, lunix light and Peppermint 8 Eight. It is forbidden to edit the original files until the material is assigned to me as the person who released the generated product under Apache-2.0
