# These are supported funding model platforms

gmail email: # Griggorii@gmail.com not collabration job google corporation


I can port various tools, I need disks and a lot of space and some kind of cool corporation which needs not an employee wiping his pants at work, but the result of really generated computers of files, and not flood my eyes with tons of code that then may not be preregistered, in particular, I am that very worker X who created a lot, but is waiting for investment, not theft of technology and rewriting
